"""Reconcile the Windows queue without deleting jobs or resetting preferences."""

from .config import LOCAL_URL, PRINTER_NAME, PRINTER_UUID


def configure_queue_script(owned_port: str) -> str:
    def quote(value: str) -> str:
        return "'" + value.replace("'", "''") + "'"

    variables = (
        f"$name={quote(PRINTER_NAME)}; $url={quote(LOCAL_URL)}; "
        f"$uuid={quote(PRINTER_UUID.removeprefix('urn:uuid:'))}; "
        f"$ownedPort={quote(owned_port)}; "
    )
    return variables + r"""
function Get-LabQueue {
    # Enumerate first: a missing name is normal, a spooler failure is not.
    Get-Printer -ErrorAction Stop | Where-Object { $_.Name -eq $name }
}
function Test-LabQueue($printer) {
    if (-not $printer -or $printer.DriverName -ne 'Microsoft IPP Class Driver') {
        return $false
    }
    $port = [string]$printer.PortName
    $portUuid = ''
    $addresses = @()
    if ($port -match '^WSD-[0-9a-f-]+$') {
        # WSD port names are generated by Windows and can change on repair.
        $key = 'HKLM:\SYSTEM\CurrentControlSet\Control\Print\Monitors\WSD Port\Ports\' + $port
        $metadata = Get-ItemProperty -LiteralPath $key -ErrorAction SilentlyContinue
        if ($metadata) { $portUuid = ([string]$metadata.'Printer UUID').Trim('{}') }
        if ($portUuid -eq $uuid) { return $true }
        if ($portUuid -match '^[0-9a-f-]{36}$') {
            $device = 'SWD\IPP\' + $portUuid
            $properties = Get-PnpDeviceProperty -InstanceId $device -ErrorAction SilentlyContinue
            $addresses = @($properties | Where-Object {
                $_.Type -eq 'String' -and $_.Data -eq $url
            })
        }
    }
    # Recover a lost/stale per-user settings file from the installed device.
    if ($portUuid -eq $uuid -or $addresses.Count -gt 0 -or $port -eq $url) {
        return $true
    }
    # Older Windows versions may not expose the device metadata. Keep the
    # recorded port as a fallback, but never override a different known UUID.
    return (-not $portUuid -and $ownedPort -and $port -eq $ownedPort)
}
$printer = Get-LabQueue
$created = $false
if (-not $printer) {
    # A user may have renamed the existing queue. Reuse it instead of adding
    # another connection to the same device.
    $candidates = @(Get-Printer -ErrorAction Stop | Where-Object { Test-LabQueue $_ })
    if ($candidates.Count -eq 1) {
        Rename-Printer -InputObject $candidates[0] -NewName $name -ErrorAction Stop
        $printer = Get-LabQueue
    } else {
        try {
            Add-Printer -Name $name -IppURL $url -ErrorAction Stop
            $created = $true
        } catch {
            # Windows may finish creating the queue before reporting failure,
            # or another installer may have completed it in the meantime.
            $printer = Get-LabQueue
            if (-not (Test-LabQueue $printer)) { throw }
        }
        for ($attempt = 0; $attempt -lt 30; $attempt++) {
            $printer = Get-LabQueue
            if ($printer) { break }
            Start-Sleep -Milliseconds 500
        }
    }
}
if (-not $printer) { throw 'Windows 尚未完成打印机配置，请稍后重新安装。' }
if ($printer.DriverName -ne 'Microsoft IPP Class Driver') {
    throw '同名打印机使用其他驱动，请先将它重命名，再安装实验室打印机。'
}
if (-not $created -and -not (Test-LabQueue $printer)) {
    throw '同名打印机连接到其他设备，请先将它重命名，再安装实验室打印机。'
}
# Defaults belong to first installation only. Reinstall preserves user choices,
# the default printer, the queue identity, and pending jobs.
if ($created) {
    Set-PrintConfiguration -PrinterName $name -PaperSize A4 -Color $false -DuplexingMode OneSided
}
$printer | Select-Object Name,PortName,DriverName | ConvertTo-Json -Compress
"""
