name: Checks
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.17"
      - run: uv sync --locked
      - run: uv run --locked ruff check .
      - run: uv run --locked pytest
      - run: uv build
